openapi: 3.0.0
servers:
  - description: Cluster Endpoint
    url: /api
info:
  description: Department List management for Web-In-Cloud system
  version: "1.0.0"
  title: Waiting List Api
  contact:
    email: <your_email>
  license:
    name: CC BY 4.0
    url: "https://creativecommons.org/licenses/by/4.0/"
tags:
 - name: departmentList
   description: Department List API

paths:
  /list:
    get:
      summary: Provides the ambulance waiting list
      operationId: getList
      description: By using ambulanceId you get list of entries in ambulance waiting list
      parameters:
        - name: ambulanceId
          in: query
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Value of the waiting list entries
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    patientId:
                      type: integer
                      format: int64
                      description: Unique id of the patient in waiting list
                    firstname:
                      type: string
                      description: Name of patient in waiting list
                    surname:
                      type: string
                      description: Surname of patient in waiting list
                    department:
                      type: string
                      description: Department of patient in waiting list
                    appointmentDate:
                      type: string
                      format: date-time
                      description: Date of appointment of patient in waiting list
                    duration:
                      type: integer
                      format: int32
                      description: Duration of appointment of patient in waiting list
      examples:
        response:
          $ref: '#/components/examples/DepartmentListExample'
        '404':
          description: Invalid something

components:
 schemas:
   DepartmentList:
     type: object
     required: [patientId, firstname, surname, department, appointmentDate, duration]
     properties:
       patientId:
         type: integer
         format: int64
         example: 1
         description: Unique id of the patient in waiting list
       firstname:
         type: string
         example: Jožko
         description: Name of patient in waiting list
       surname:
         type: string
         example: Mrkvicka
         description: Surname of patient in waiting list

       department:
         type: string
         example: Surgery
         description: Department of patient in waiting list

       appointmentDate:
         type: string
         format: date-time
         example: "2038-12-24T10:05:00Z"
         description: Date of appointment of patient in waiting list

       duration:
         type: integer
         format: int32 
         example: 15
         description: Duration of appointment of patient in waiting list
       
   examples:
    DepartmentListExample:
      value:
        - patientId: 1
          firstname: Jožko
          surname: Mrkvicka
          department: Surgery
          appointmentDate: "2038-12-24T10:05:00Z"
          duration: 15
        - patientId: 2
          firstname: Janko
          surname: Hraško
          department: Surgery
          appointmentDate: "2038-12-24T10:20:00Z"
          duration: 30
        - patientId: 3
          firstname: Ferko
          surname: Mrkvička
          department: Surgery
          appointmentDate: "2038-12-24T10:35:00Z"
          duration: 60